### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by lazappi**
This PR contains the most recent version of the website including the most recent results, plots etc. It can be viewed at https://optimistic-noyce-d9e8b7.netlify.app/.

### CODE REVIEW

**Comment by lazappi** [comment]
Not sure how to review this but you can view the development version I guess?

**Comment by LuckyMD** [comment]
Hahaha, a casual 2,465 files to review ;). Instead, sticking to the website to review thing I noticed a nice change of colour scheme in the ATAC batch embedding plots :). And MNN and Scanorama have the correct batch labels. Only 1 minor thing, you say 17 methods were tested in the home page. I think you might be counting "unintegrated" as a method there. It should be 16. Assuming you will change this, I will approve the PR already :).

**Review by LuckyMD — APPROVED** [review]
1 change from 17 -> 16 methods that were tested, but otherwise looks awesome!

**Comment by lazappi** [comment]
Should be fixed now but think you will need to mark as reviewed again.

**Review by LuckyMD — APPROVED** [review]

**Comment by LuckyMD** [comment]
nice :)

**Pull request merged**
