### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by lazappi**
Rebuild the website with the latest metric scores.

Also adds a note to the usability page to address #5. 

Preview at https://6065e329728764000767e65f--optimistic-noyce-d9e8b7.netlify.app/

### CODE REVIEW

**Comment by LuckyMD** [comment]
you star :)

**Comment by LuckyMD** [comment]
A few comments:
1. Do you think the usability note should be so prominent in the top or rather at the bottom?
2. Could you order the methods in the usability section by overall usability?

**Comment by lazappi** [comment]
So turns out the overall package/paper usability scores weren't actually there at all... I've added those to the table and made them the default sorting. I also added the DOIs to the paper table (mostly so it is clear which are preprints that might have been published since then).

I toned down the note about things being out of date but left it at the top. Let me know if you want to adjust it more.

**Comment by LuckyMD** [comment]
I really like the usability section with all the explanations. I think once the exact date is added this can be merged!

**Review by LuckyMD — DISMISSED** [review]
Awesome website! Just update to 17th December 2020 as the usability deadline

**Comment by lazappi** [comment]
Should be done now but use this link to check, I think I put the wrong on at the top https://website--optimistic-noyce-d9e8b7.netlify.app/index.html

**Comment by lazappi** [comment]
@LuckyMD Updated the usability notice and modified the tables so that the columns for method etc. are frozen.

**Comment by LuckyMD** [comment]
Dayummm... this is awesome, you are awesome! I love it. Ready to merge from my side!

**Review by LuckyMD — APPROVED** [review]
awesome website update!

**Comment by LuckyMD** [comment]
Merge when you're ready.

**Pull request merged**
